/**
 * 自动生成侧边栏配置脚本
 * 
 * 功能：
 * 1. 扫描 src/ 目录下的 Markdown 文件
 * 2. 根据目录结构自动生成侧边栏配置
 * 3. 支持多级目录嵌套
 * 4. 自动提取 frontmatter 中的 title 作为导航标题
 * 
 * 使用方式：
 * pnpm tsx scripts/generate-sidebar.ts
 */

import fs from 'node:fs'
import path from 'node:path'
import type { DefaultTheme } from 'vitepress'

interface SidebarConfig {
  [route: string]: DefaultTheme.SidebarItem[]
}

/**
 * 从 Markdown 文件中提取 frontmatter 的 title
 */
function extractTitle(filePath: string): string {
  const content = fs.readFileSync(filePath, 'utf-8')
  const frontmatterMatch = content.match(/^---\s*\n([\s\S]*?)\n---/)
  
  if (frontmatterMatch) {
    const titleMatch = frontmatterMatch[1].match(/title:\s*['"]?(.+?)['"]?\s*\n/)
    if (titleMatch) return titleMatch[1]
  }
  
  // 如果没有 frontmatter，使用文件名
  return path.basename(filePath, '.md')
    .split('-')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

/**
 * 递归扫描目录生成侧边栏项
 */
function generateSidebarItems(dir: string, baseDir: string): DefaultTheme.SidebarItem[] {
  const items: DefaultTheme.SidebarItem[] = []
  const files = fs.readdirSync(dir, { withFileTypes: true })
  
  // 先处理文件夹，再处理文件
  const dirs = files.filter(f => f.isDirectory())
  const mdFiles = files.filter(f => f.isFile() && f.name.endsWith('.md') && f.name !== 'index.md')
  
  // 处理子目录
  for (const subDir of dirs) {
    const subDirPath = path.join(dir, subDir.name)
    const subItems = generateSidebarItems(subDirPath, baseDir)
    
    if (subItems.length > 0) {
      items.push({
        text: subDir.name.charAt(0).toUpperCase() + subDir.name.slice(1),
        collapsed: false,
        items: subItems
      })
    }
  }
  
  // 处理 Markdown 文件
  for (const file of mdFiles) {
    const filePath = path.join(dir, file.name)
    const relativePath = path.relative(baseDir, filePath)
      .replace(/\\/g, '/')
      .replace(/\.md$/, '')
    
    items.push({
      text: extractTitle(filePath),
      link: `/${relativePath}`
    })
  }
  
  return items
}

/**
 * 生成完整的侧边栏配置
 */
function generateSidebarConfig(srcDir: string): SidebarConfig {
  const config: SidebarConfig = {}
  
  // 扫描 src 目录下的一级目录
  const entries = fs.readdirSync(srcDir, { withFileTypes: true })
  const topDirs = entries.filter(e => e.isDirectory())
  
  for (const dir of topDirs) {
    const dirPath = path.join(srcDir, dir.name)
    const items = generateSidebarItems(dirPath, srcDir)
    
    if (items.length > 0) {
      config[`/${dir.name}/`] = items
    }
  }
  
  return config
}

/**
 * 主函数
 */
function main() {
  const rootDir = path.resolve(__dirname, '..')
  const srcDir = path.join(rootDir, 'src')
  
  if (!fs.existsSync(srcDir)) {
    console.error('❌ src/ 目录不存在')
    process.exit(1)
  }
  
  const config = generateSidebarConfig(srcDir)
  
  // 生成配置文件内容
  const output = `/**
 * 自动生成的侧边栏配置
 * 
 * ⚠️ 此文件由 scripts/generate-sidebar.ts 自动生成
 * 请勿手动修改！如需更新，请运行：pnpm tsx scripts/generate-sidebar.ts
 * 
 * 生成时间：${new Date().toLocaleString('zh-CN')}
 */

import type { DefaultTheme } from 'vitepress'

export const autoGeneratedSidebar: DefaultTheme.Sidebar = ${JSON.stringify(config, null, 2)}
`
  
  const outputPath = path.join(rootDir, '.vitepress/config/sidebar/auto-generated.ts')
  fs.writeFileSync(outputPath, output, 'utf-8')
  
  console.log('✅ 侧边栏配置生成成功：', outputPath)
  console.log('📊 生成的路由数量：', Object.keys(config).length)
}

main()
